name: primer workflow

on:
  push:
    branches:
      - feature/draft

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run:
          echo "Hola al primer workflow"
      - name: Obtener la fecha
        run: date
      - run: ls -l

      