name: primer workflow

on:
  push:
    branches:
      - develop

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run:
          echo "Hola al primer workflow"